### ISSUE TITLE
Containers & security

### ISSUE THREAD

**Issue by zcorleissen** [getcarina/getcarina.com#31]

**Comment by rose-coste** [comment]
Security Best Practices article is now set for Milestone 2. When we get back to it, make sure it's consistent with or connected to http://blog.rackspace.com/tech-deep-dive-with-carina-magnum-containers/#comment-2342692424, Adrian Otto's extensive response to a security-related question about his general Carina article.

**Comment by lauracly** [comment]
@major @rgbkrk - is this content ready for the M1+ milestone? Can we repurpose it into a conceptual article? Can you provide any updates?

**Comment by rgbkrk** [comment]
This content went in it looks like, then promptly tossed at some point by an aberrant merge commit. I can bring it over again.

**Comment by lauracly** [comment]
@rgbkrk did this get added back in? Can you give an update?

**Comment by rgbkrk** [comment]
It's here actually: https://github.com/getcarina/getcarina.com/blob/master/_M2/001-container-security.md

**Comment by lauracly** [comment]
Great - it doesn't look like that one is live on the site. Is it ready to publish?

**Comment by rgbkrk** [comment]
Seems fine to me. We can iterate on it further after publication.

**Comment by lauracly** [comment]
Checked with Kelly - she hasn't edited it yet.  I think we should send to her and have her give edits, and then push out. Sound good? I gave her the heads up to go ahead and edit it.

**Comment by kmsholcomb** [comment]
Hi @major @rgbkrk @lauracly: The attached Word doc contains my editorial markup for the article. All in all, my markup is pretty light! My main concern is that the beginning of the article is a bit confusing because it does not provide a clear introduction to the article and provides two links without sufficient context. I think that could be cleared up pretty easily. I also left a note at the end of the file regarding the comment posted by @rose-coste in this issue thread. Please let me know if you have any questions. Thanks!

[Container security_editsKH.docx](https://github.com/getcarina/getcarina.com/files/92302/Container.security_editsKH.docx)

**Comment by lauracly** [comment]
@rgbkrk are you entering the edits from Kelly?

**Comment by rgbkrk** [comment]
Not right now, currently working on blog posts that are tagged for me to complete.

**Comment by lauracly** [comment]
I can sign up for the basic edits, but there are a few questions in there that the author must answer. @rgbkrk is that you, or should @major answer them?

**Comment by everett-toews** [comment]
I'll try to get to this tomorrow.

**Comment by everett-toews** [comment]
@lauracly Sorry I missed your earlier comment. How about we team up? 

Can you do the basic edits and I'll do the bigger picture questions?

**Comment by lauracly** [comment]
@everett-toews yes let's do that. I can get the edits done today, and then pass along to you for the follow up questions. Sound good?

**Comment by everett-toews** [comment]
@lauracly SGTM!

**Comment by lauracly** [comment]
Edits are in file, and merged. @everett-toews you can disposition the questions directly into the updated base article.
