### ISSUE TITLE
Does it run Minecraft?

### ISSUE THREAD

**Issue by everett-toews** [getcarina/getcarina.com#564]
Create a tutorial for Minecraft and Dockercraft.

**Comment by kenperkins** [comment]
I love this idea!

I'm wondering if you're planning to do it in a way as to make doing it on Carina novel, and not just "do it on carina", but otherwise not really different from other articles on minecraft on docker.

Off the cuff possibilities:

- stateless deployment where the minecraft data is stored in the cloud (i have no idea how this would work)
- multi container cluster where you federate different minecraft roles to different containers, map view app container, admin web app container, server proper, etc
- ephemeral minecraft worlds on demand, tmpnb style where you get a server
- ... other?

**Comment by everett-toews** [comment]
@kenperkins and I discussed this and agreed that these might make good supplemental tutorials to a basic tutorial getting Minecraft up and running on Carina.
